INSERT INTO countries(name, created_at, updated_at) VALUES ('Afghanistan', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Aland Islands', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Albania', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Algeria', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('American Samoa', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Andorra', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Angola', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Anguilla', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Antarctica', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Antigua And Barbuda', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Argentina', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Armenia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Aruba', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Australia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Austria', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Azerbaijan', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Bahrain', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Bangladesh', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Barbados', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Belarus', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Belgium', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Belize', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Benin', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Bermuda', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Bhutan', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Bolivia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Bonaire, Sint Eustatius and Saba', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Bosnia and Herzegovina', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Botswana', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Bouvet Island', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Brazil', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('British Indian Ocean Territory', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Brunei', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Bulgaria', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Burkina Faso', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Burundi', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Cambodia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Cameroon', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Canada', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Cape Verde', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Cayman Islands', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Central African Republic', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Chad', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Chile', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('China', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Christmas Island', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Cocos (Keeling) Islands', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Colombia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Comoros', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Congo', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Cook Islands', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Costa Rica', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Cote D''Ivoire (Ivory Coast)', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Croatia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Cuba', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Curaçao', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Cyprus', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Czech Republic', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Democratic Republic of the Congo', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Denmark', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Djibouti', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Dominica', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Dominican Republic', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('East Timor', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Ecuador', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Egypt', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('El Salvador', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Equatorial Guinea', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Eritrea', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Estonia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Ethiopia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Falkland Islands', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Faroe Islands', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Fiji Islands', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Finland', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('France', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('French Guiana', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('French Polynesia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('French Southern Territories', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Gabon', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Gambia The', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Georgia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Germany', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Ghana', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Gibraltar', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Greece', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Greenland', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Grenada', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Guadeloupe', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Guam', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Guatemala', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Guernsey and Alderney', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Guinea', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Guinea-Bissau', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Guyana', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Haiti', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Heard Island and McDonald Islands', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Honduras', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Hong Kong S.A.R.', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Hungary', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Iceland', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('India', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Indonesia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Iran', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Iraq', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Ireland', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Israel', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Italy', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Jamaica', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Japan', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Jersey', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Jordan', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Kazakhstan', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Kenya', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Kiribati', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Kosovo', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Kuwait', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Kyrgyzstan', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Laos', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Latvia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Lebanon', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Lesotho', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Liberia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Libya', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Liechtenstein', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Lithuania', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Luxembourg', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Macau S.A.R.', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Madagascar', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Malawi', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Malaysia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Maldives', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Mali', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Malta', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Man (Isle of)', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Marshall Islands', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Martinique', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Mauritania', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Mauritius', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Mayotte', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Mexico', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Micronesia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Moldova', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Monaco', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Mongolia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Montenegro', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Montserrat', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Morocco', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Mozambique', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Myanmar', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Namibia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Nauru', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Nepal', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Netherlands', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('New Caledonia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('New Zealand', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Nicaragua', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Niger', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Nigeria', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Niue', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Norfolk Island', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('North Korea', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('North Macedonia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Northern Mariana Islands', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Norway', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Oman', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Pakistan', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Palau', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Palestinian Territory Occupied', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Panama', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Papua new Guinea', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Paraguay', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Peru', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Philippines', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Pitcairn Island', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Poland', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Portugal', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Puerto Rico', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Qatar', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Reunion', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Romania', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Russia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Rwanda', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Saint Helena', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Saint Kitts And Nevis', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Saint Lucia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Saint Pierre and Miquelon', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Saint Vincent And The Grenadines', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Saint-Barthelemy', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Saint-Martin (French part)', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Samoa', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('San Marino', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Sao Tome and Principe', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Saudi Arabia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Senegal', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Serbia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Seychelles', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Sierra Leone', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Singapore', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Sint Maarten (Dutch part)', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Slovakia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Slovenia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Solomon Islands', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Somalia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('South Africa', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('South Georgia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('South Korea', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('South Sudan', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Spain', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Sri Lanka', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Sudan', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Suriname', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Svalbard And Jan Mayen Islands', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Swaziland', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Sweden', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Switzerland', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Syria', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Taiwan', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Tajikistan', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Tanzania', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Thailand', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('The Bahamas', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Togo', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Tokelau', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Tonga', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Trinidad And Tobago', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Tunisia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Turkey', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Turkmenistan', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Turks And Caicos Islands', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Tuvalu', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Uganda', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Ukraine', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('United Arab Emirates', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('United Kingdom', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('United States', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('United States Minor Outlying Islands', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Uruguay', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Uzbekistan', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Vanuatu', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Vatican City State (Holy See)', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Venezuela', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Vietnam', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Virgin Islands (British)', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Virgin Islands (US)', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Wallis And Futuna Islands', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Western Sahara', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Yemen', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Zambia', GETDATE(), GETDATE());
INSERT INTO countries(name, created_at, updated_at) VALUES ('Zimbabwe', GETDATE(), GETDATE());
