INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Afghanis,tan',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Aland Islands',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Albania',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Algeria',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('American Samoa',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Andorra',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Angola',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Anguilla',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Antarctica',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Antigua And Barbuda',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Argentina',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Armenia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Aruba',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Australia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Austria',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Azerbaijan',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bahrain',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bangladesh',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Barbados',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Belarus',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Belgium',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Belize',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Benin',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bermuda',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bhutan',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bolivia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bonaire,Sint Eustatius and Saba',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bosnia and Herzegovina',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Botswana',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bouvet Island',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Brazil',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('British Indian Ocean Territory',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Brunei',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bulgaria',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Burkina Faso',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Burundi',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cambodia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cameroon',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Canada',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cape Verde',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cayman Islands',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Central African Republic',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Chad',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Chile',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('China',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Christmas Island',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cocos (Keeling) Islands',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Colombia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Comoros',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Congo',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cook Islands',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Costa Rica',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cote D''Ivoire (Ivory Coast)',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Croatia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cuba',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Curaçao',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cyprus',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Czech Republic',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Democratic Republic of the Congo',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Denmark',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Djibouti',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Dominica',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Dominican Republic',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('East Timor',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ecuador',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Egypt',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('El Salvador',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Equatorial Guinea',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Eritrea',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Estonia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ethiopia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Falkland Islands',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Faroe Islands',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Fiji Islands',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Finland',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('France',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('French Guiana',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('French Polynesia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('French Southern Territories',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Gabon',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Gambia The',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Georgia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Germany',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ghana',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Gibraltar',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Greece',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Greenland',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Grenada',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guadeloupe',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guam',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guatemala',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guernsey and Alderney',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guinea',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guinea-Bissau',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guyana',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Haiti',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Heard Island and McDonald Islands',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Honduras',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Hong Kong S.A.R.',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Hungary',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Iceland',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('India',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Indonesia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Iran',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Iraq',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ireland',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Israel',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Italy',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Jamaica',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Japan',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Jersey',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Jordan',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kazakhstan',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kenya',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kiribati',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kosovo',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kuwait',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kyrgyzstan',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Laos',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Latvia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Lebanon',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Lesotho',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Liberia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Libya',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Liechtenstein',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Lithuania',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Luxembourg',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Macau S.A.R.',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Madagascar',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Malawi',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Malaysia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Maldives',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mali',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Malta',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Man (Isle of)',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Marshall Islands',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Martinique',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mauritania',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mauritius',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mayotte',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mexico',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Micronesia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Moldova',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Monaco',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mongolia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Montenegro',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Montserrat',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Morocco',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mozambique',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Myanmar',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Namibia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Nauru',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Nepal',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Netherlands',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('New Caledonia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('New Zealand',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Nicaragua',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Niger',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Nigeria',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Niue',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Norfolk Island',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('North Korea',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('North Macedonia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Northern Mariana Islands',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Norway',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Oman',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Pakistan',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Palau',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Palestinian Territory Occupied',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Panama',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Papua new Guinea',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Paraguay',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Peru',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Philippines',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Pitcairn Island',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Poland',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Portugal',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Puerto Rico',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Qatar',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Reunion',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Romania',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Russia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Rwanda',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Helena',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Kitts And Nevis',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Lucia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Pierre and Miquelon',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Vincent And The Grenadines',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint-Barthelemy',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint-Martin (French part)',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Samoa',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('San Marino',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sao Tome and Principe',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saudi Arabia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Senegal',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Serbia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Seychelles',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sierra Leone',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Singapore',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sint Maarten (Dutch part)',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Slovakia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Slovenia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Solomon Islands',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Somalia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('South Africa',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('South Georgia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('South Korea',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('South Sudan',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Spain',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sri Lanka',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sudan',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Suriname',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Svalbard And Jan Mayen Islands',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Swaziland',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sweden',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Switzerland',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Syria',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Taiwan',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tajikistan',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tanzania',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Thailand',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('The Bahamas',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Togo',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tokelau',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tonga',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Trinidad And Tobago',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tunisia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Turkey',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Turkmenistan',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Turks And Caicos Islands',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tuvalu',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Uganda',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ukraine',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('United Arab Emirates',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('United Kingdom',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('United States',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('United States Minor Outlying Islands',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Uruguay',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Uzbekistan',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Vanuatu',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Vatican City State (Holy See)',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Venezuela',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Vietnam',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Virgin Islands (British)',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Virgin Islands (US)',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Wallis And Futuna Islands',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Western Sahara',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Yemen',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Zambia',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Zimbabwe',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
