INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Afghanistan',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Aland Islands',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Albania',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Algeria',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('American Samoa',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Andorra',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Angola',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Anguilla',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Antarctica',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Antigua And Barbuda',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Argentina',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Armenia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Aruba',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Australia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Austria',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Azerbaijan',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bahrain',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bangladesh',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Barbados',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Belarus',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Belgium',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Belize',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Benin',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bermuda',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bhutan',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bolivia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bonaire,Sint Eustatius and Saba',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bosnia and Herzegovina',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Botswana',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bouvet Island',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Brazil',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('British Indian Ocean Territory',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Brunei',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Bulgaria',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Burkina Faso',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Burundi',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cambodia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cameroon',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Canada',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cape Verde',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cayman Islands',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Central African Republic',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Chad',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Chile',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('China',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Christmas Island',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cocos (Keeling) Islands',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Colombia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Comoros',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Congo',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cook Islands',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Costa Rica',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cote D''Ivoire (Ivory Coast)',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Croatia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cuba',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Curaçao',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Cyprus',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Czech Republic',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Democratic Republic of the Congo',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Denmark',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Djibouti',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Dominica',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Dominican Republic',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('East Timor',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ecuador',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Egypt',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('El Salvador',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Equatorial Guinea',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Eritrea',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Estonia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ethiopia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Falkland Islands',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Faroe Islands',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Fiji Islands',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Finland',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('France',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('French Guiana',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('French Polynesia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('French Southern Territories',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Gabon',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Gambia The',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Georgia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Germany',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ghana',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Gibraltar',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Greece',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Greenland',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Grenada',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guadeloupe',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guam',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guatemala',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guernsey and Alderney',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guinea',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guinea-Bissau',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Guyana',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Haiti',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Heard Island and McDonald Islands',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Honduras',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Hong Kong S.A.R.',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Hungary',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Iceland',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('India',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Indonesia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Iran',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Iraq',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ireland',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Israel',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Italy',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Jamaica',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Japan',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Jersey',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Jordan',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kazakhstan',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kenya',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kiribati',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kosovo',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kuwait',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Kyrgyzstan',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Laos',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Latvia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Lebanon',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Lesotho',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Liberia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Libya',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Liechtenstein',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Lithuania',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Luxembourg',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Macau S.A.R.',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Madagascar',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Malawi',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Malaysia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Maldives',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mali',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Malta',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Man (Isle of)',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Marshall Islands',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Martinique',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mauritania',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mauritius',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mayotte',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mexico',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Micronesia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Moldova',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Monaco',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mongolia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Montenegro',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Montserrat',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Morocco',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Mozambique',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Myanmar',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Namibia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Nauru',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Nepal',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Netherlands',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('New Caledonia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('New Zealand',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Nicaragua',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Niger',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Nigeria',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Niue',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Norfolk Island',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('North Korea',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('North Macedonia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Northern Mariana Islands',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Norway',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Oman',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Pakistan',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Palau',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Palestinian Territory Occupied',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Panama',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Papua new Guinea',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Paraguay',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Peru',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Philippines',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Pitcairn Island',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Poland',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Portugal',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Puerto Rico',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Qatar',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Reunion',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Romania',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Russia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Rwanda',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Helena',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Kitts And Nevis',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Lucia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Pierre and Miquelon',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint Vincent And The Grenadines',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint-Barthelemy',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saint-Martin (French part)',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Samoa',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('San Marino',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sao Tome and Principe',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Saudi Arabia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Senegal',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Serbia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Seychelles',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sierra Leone',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Singapore',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sint Maarten (Dutch part)',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Slovakia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Slovenia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Solomon Islands',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Somalia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('South Africa',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('South Georgia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('South Korea',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('South Sudan',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Spain',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sri Lanka',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sudan',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Suriname',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Svalbard And Jan Mayen Islands',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Swaziland',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Sweden',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Switzerland',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Syria',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Taiwan',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tajikistan',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tanzania',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Thailand',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('The Bahamas',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Togo',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tokelau',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tonga',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Trinidad And Tobago',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tunisia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Turkey',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Turkmenistan',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Turks And Caicos Islands',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Tuvalu',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Uganda',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Ukraine',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('United Arab Emirates',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('United Kingdom',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('United States',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('United States Minor Outlying Islands',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Uruguay',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Uzbekistan',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Vanuatu',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Vatican City State (Holy See)',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Venezuela',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Vietnam',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Virgin Islands (British)',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Virgin Islands (US)',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Wallis And Futuna Islands',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Western Sahara',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Yemen',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Zambia',false,GETDATE(),GETDATE());
INSERT INTO countries(name,is_deleted,created_at,updated_at) VALUES ('Zimbabwe',false,GETDATE(),GETDATE());
