document.addEventListener("DOMContentLoaded", function () {
  // Inicializar ordenes compra
  let ordenesCompra = JSON.parse(localStorage.getItem("ordenesCompra"));

  if (!ordenesCompra) {
    ordenesCompra = [
      {
        numero: "1",
        fechaEmision: "2023-01-01",
        fechaEntrega: "2023-01-10",
        direccion: "Calle A, N° 123",
        proveedor: "Proveedor 1",
        productos: "Producto 1, Producto 2",
        cantidad: "2, 3",
        total: 72.95,
      },
      {
        numero: "2",
        fechaEmision: "2023-02-05",
        fechaEntrega: "2023-02-15",
        direccion: "Calle B, N° 456",
        proveedor: "Proveedor 2",
        productos: "Producto 3, Producto 4",
        cantidad: "1, 4",
        total: 105.75,
      },
      {
        numero: "3",
        fechaEmision: "2023-03-12",
        fechaEntrega: "2023-03-22",
        direccion: "Calle C, N° 789",
        proveedor: "Proveedor 3",
        productos: "Producto 5, Producto 6",
        cantidad: "3, 2",
        total: 54.2,
      },
      {
        numero: "4",
        fechaEmision: "2023-04-18",
        fechaEntrega: "2023-04-28",
        direccion: "Calle D, N° 1011",
        proveedor: "Proveedor 1",
        productos: "Producto 7, Producto 8",
        cantidad: "5, 1",
        total: 91.4,
      },
      {
        numero: "5",
        fechaEmision: "2023-05-24",
        fechaEntrega: "2023-06-03",
        direccion: "Calle E, N° 1213",
        proveedor: "Proveedor 2",
        productos: "Producto 9, Producto 10",
        cantidad: "2, 3",
        total: 67.8,
      },
      {
        numero: "6",
        fechaEmision: "2023-06-30",
        fechaEntrega: "2023-07-10",
        direccion: "Calle F, N° 1415",
        proveedor: "Proveedor 3",
        productos: "Producto 11, Producto 12",
        cantidad: "4, 2",
        total: 89.6,
      },
      {
        numero: "7",
        fechaEmision: "2023-07-15",
        fechaEntrega: "2023-07-25",
        direccion: "Calle G, N° 1617",
        proveedor: "Proveedor 1",
        productos: "Producto 13, Producto 14",
        cantidad: "2, 3",
        total: 76.45,
      },
      {
        numero: "8",
        fechaEmision: "2023-08-20",
        fechaEntrega: "2023-08-30",
        direccion: "Calle H, N° 1819",
        proveedor: "Proveedor 2",
        productos: "Producto 15, Producto 16",
        cantidad: "1, 4",
        total: 112.3,
      },
      {
        numero: "9",
        fechaEmision: "2023-09-25",
        fechaEntrega: "2023-10-05",
        direccion: "Calle I, N° 2021",
        proveedor: "Proveedor 3",
        productos: "Producto 17, Producto 18",
        cantidad: "3, 2",
        total: 59.1,
      },
      {
        numero: "10",
        fechaEmision: "2023-10-31",
        fechaEntrega: "2023-11-10",
        direccion: "Calle J, N° 2223",
        proveedor: "Proveedor 1",
        productos: "Producto 19, Producto 20",
        cantidad: "5, 1",
        total: 97.8,
      },
    ];

    localStorage.setItem("ordenesCompra", JSON.stringify(ordenesCompra));
  }
});
