INSERT INTO countries(name,created_at,updated_at) VALUES ('Afghanis,tan',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Aland Islands',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Albania',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Algeria',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('American Samoa',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Andorra',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Angola',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Anguilla',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Antarctica',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Antigua And Barbuda',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Argentina',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Armenia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Aruba',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Australia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Austria',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Azerbaijan',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Bahrain',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Bangladesh',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Barbados',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Belarus',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Belgium',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Belize',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Benin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Bermuda',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Bhutan',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Bolivia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Bonaire,Sint Eustatius and Saba',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Bosnia and Herzegovina',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Botswana',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Bouvet Island',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Brazil',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('British Indian Ocean Territory',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Brunei',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Bulgaria',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Burkina Faso',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Burundi',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Cambodia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Cameroon',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Canada',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Cape Verde',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Cayman Islands',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Central African Republic',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Chad',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Chile',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('China',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Christmas Island',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Cocos (Keeling) Islands',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Colombia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Comoros',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Congo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Cook Islands',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Costa Rica',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Cote D''Ivoire (Ivory Coast)',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Croatia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Cuba',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Curaçao',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Cyprus',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Czech Republic',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Democratic Republic of the Congo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Denmark',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Djibouti',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Dominica',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Dominican Republic',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('East Timor',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Ecuador',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Egypt',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('El Salvador',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Equatorial Guinea',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Eritrea',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Estonia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Ethiopia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Falkland Islands',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Faroe Islands',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Fiji Islands',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Finland',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('France',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('French Guiana',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('French Polynesia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('French Southern Territories',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Gabon',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Gambia The',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Georgia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Germany',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Ghana',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Gibraltar',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Greece',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Greenland',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Grenada',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Guadeloupe',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Guam',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Guatemala',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Guernsey and Alderney',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Guinea',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Guinea-Bissau',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Guyana',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Haiti',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Heard Island and McDonald Islands',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Honduras',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Hong Kong S.A.R.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Hungary',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Iceland',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('India',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Indonesia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Iran',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Iraq',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Ireland',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Israel',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Italy',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Jamaica',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Japan',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Jersey',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Jordan',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Kazakhstan',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Kenya',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Kiribati',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Kosovo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Kuwait',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Kyrgyzstan',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Laos',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Latvia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Lebanon',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Lesotho',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Liberia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Libya',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Liechtenstein',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Lithuania',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Luxembourg',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Macau S.A.R.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Madagascar',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Malawi',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Malaysia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Maldives',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Mali',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Malta',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Man (Isle of)',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Marshall Islands',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Martinique',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Mauritania',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Mauritius',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Mayotte',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Mexico',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Micronesia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Moldova',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Monaco',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Mongolia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Montenegro',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Montserrat',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Morocco',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Mozambique',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Myanmar',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Namibia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Nauru',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Nepal',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Netherlands',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('New Caledonia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('New Zealand',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Nicaragua',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Niger',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Nigeria',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Niue',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Norfolk Island',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('North Korea',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('North Macedonia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Northern Mariana Islands',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Norway',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Oman',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Pakistan',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Palau',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Palestinian Territory Occupied',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Panama',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Papua new Guinea',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Paraguay',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Peru',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Philippines',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Pitcairn Island',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Poland',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Portugal',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Puerto Rico',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Qatar',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Reunion',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Romania',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Russia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Rwanda',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Saint Helena',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Saint Kitts And Nevis',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Saint Lucia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Saint Pierre and Miquelon',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Saint Vincent And The Grenadines',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Saint-Barthelemy',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Saint-Martin (French part)',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Samoa',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('San Marino',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Sao Tome and Principe',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Saudi Arabia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Senegal',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Serbia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Seychelles',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Sierra Leone',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Singapore',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Sint Maarten (Dutch part)',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Slovakia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Slovenia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Solomon Islands',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Somalia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('South Africa',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('South Georgia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('South Korea',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('South Sudan',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Spain',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Sri Lanka',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Sudan',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Suriname',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Svalbard And Jan Mayen Islands',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Swaziland',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Sweden',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Switzerland',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Syria',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Taiwan',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Tajikistan',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Tanzania',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Thailand',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('The Bahamas',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Togo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Tokelau',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Tonga',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Trinidad And Tobago',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Tunisia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Turkey',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Turkmenistan',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Turks And Caicos Islands',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Tuvalu',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Uganda',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Ukraine',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('United Arab Emirates',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('United Kingdom',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('United States',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('United States Minor Outlying Islands',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Uruguay',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Uzbekistan',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Vanuatu',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Vatican City State (Holy See)',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Venezuela',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Vietnam',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Virgin Islands (British)',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Virgin Islands (US)',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Wallis And Futuna Islands',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Western Sahara',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Yemen',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Zambia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO countries(name,created_at,updated_at) VALUES ('Zimbabwe',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
