// Suppliers
Table "suppliers" {
  "id" int [pk, increment]
  "code" varchar(255) [unique]
  "businessName" varchar(255) [unique]
  "industry" varchar(255)
  "website" varchar(255)
  "email" varchar(255)
  "phone" varchar(255)
  "address_id" int
  "tax_information_id" int
  "contact_detail_id" int
  "is_deleted" bit
}

Table "addresses" {
  "id" int [pk, increment]
  "street" varchar(255)
  "number" varchar(255)
  "postal_code" varchar(255)
  "city" varchar(255)
  "state_id" int
}

Table "state" {
  "id" int [pk, increment]
  "name" varchar(255)
  "country_id" int
}

Table "country" {
  "id" int [pk, increment]
  "name" varchar(255)
}

Table "contact_details" {
  "id" int [pk, increment]
  "first_name" varchar(255)
  "last_name" varchar(255)
  "phone" varchar(255)
  "email" varchar(255)
  "role" varchar(255)
}

Table "tax_information" {
  "id" int [pk, increment]
  "cuit" varchar(255) [unique]
  "vat_condition" varchar(255)
}

// Products
Table "products" {
  "id" int [pk, increment]
  "sku" varchar(255) [unique]
  "name" varchar(255)
  "description" varchar(255)
  "price" float
  "category_id" int
  "supplier_id" int
  "is_deleted" bit
}

Table "categories" {
  "id" int [pk, increment]
  "name" varchar(255)
}

// Orders
Table "orders" {
  "id" int [pk, increment]
  "issue_date" timestamp [default: `now()`]
  "delivery_date" date
  "comments" varchar(255)
  "total" float
  "status_id" int
  "supplier_id" int
  "is_deleted" bit
}

Table "statuses" {
  "id" int [pk, increment]
  "name" varchar(255) [note: 'Processing, Delivered, Canceled']
}

Table "order_details" {
  "id" int [pk, increment]
  "order_id" int
  "product_id" int
  "quantity" int
  "subtotal" float
}

// Users
Table "users" {
  "id" int [pk, increment]
  "first_name" varchar(255)
  "last_name" varchar(255)
  "dni" varchar(255) [unique]
  "email" varchar(255) [unique]
  "phone" varchar(255)
  "genre_id" int
  "role_id" int
  "address_id" int
  "is_deleted" bit
}

Table "genres" {
  "id" int [pk, increment]
  "name" varchar(255)
}

Table "roles" {
  "id" int [pk, increment]
  "name" varchar(255)
}

Table "user_credentials" {
  "id" int [pk, increment]
  "user_id" int
  "password_hash" varchar(255)
}

// Relationships
Ref:"suppliers"."address_id" - "addresses"."id"

Ref:"suppliers"."contact_detail_id" - "contact_details"."id"

Ref:"suppliers"."tax_information_id" - "tax_information"."id"

Ref:"suppliers"."id" < "products"."supplier_id"

Ref:"suppliers"."id" < "orders"."supplier_id"

Ref:"products"."id" < "order_details"."product_id"

Ref:"categories"."id" < "products"."category_id"

Ref:"orders"."id" < "order_details"."order_id"

Ref:"statuses"."id" < "orders"."status_id"

Ref:"users"."address_id" - "addresses"."id"

Ref:"genres"."id" < "users"."genre_id"

Ref:"roles"."id" < "users"."role_id"

Ref:"users"."id" - "user_credentials"."user_id"

Ref:"addresses"."state_id" > "state"."id"

Ref:"state"."country_id" > "country"."id"
